- name: "Check that cfg_group_name var is defined for role"
  ansible.builtin.fail:
    msg: "cfg_group_name var not defined for this role"
  when: cfg_group_name is undefined

- name: "Add group '{{ cfg_group_name }}' to the system, if it does not exist"
  ansible.builtin.group:
    name: "{{ cfg_group_name }}"
    system: "{{ cfg_group_is_system_group }}"
    state: present
  become: true
  become_user: root

