- name: "Add groups to the system, if they do not exist"
  ansible.builtin.group:
    name: "{{ cfg_group.group_name }}"
    system: "{{ cfg_group.is_system_group }}"
    state: present
  become: true
  become_user: root
  loop: "{{ cfg_groups_to_add }}"
  loop_control:
    loop_var: cfg_group
  when: cfg_groups_to_add | length > 0

- name: "Remove groups from the system, as required"
  ansible.builtin.group:
    name: "{{ cfg_group.group_name }}"
    state: absent
  become: true
  become_user: root
  loop: "{{ cfg_groups_to_remove }}"
  loop_control:
    loop_var: cfg_group
  when: cfg_groups_to_remove | length > 0

